db:
    username: ${username.value:postgres}
    password: odae4Qu
    driver: PostgresDriver
    url: postgres:5432
    hosts: localhost,127.0.0.1

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: odae4Qu
        driver-class-name: org.postgresql.Driver
